"""Static catalogue of on-disk HyperUI-style components for ingestion."""

from __future__ import annotations

CATALOGUE: dict[str, dict] = {
    "heroes/split-left": {
        "name": "Authority Split Hero",
        "category": "hero",
        "variant_name": "split-left",
        "file": "heroes/split-left.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Split layout hero with headline and supporting copy; suits professional services.",
        "mood": "professional",
        "business_types": ["law-firm", "accountancy", "consultancy"],
        "visual_tags": ["split", "image-right", "headline"],
    },
    "heroes/atmospheric": {
        "name": "Atmospheric Hero",
        "category": "hero",
        "variant_name": "atmospheric",
        "file": "heroes/atmospheric.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Full-bleed atmospheric background hero for brand-led storytelling.",
        "mood": "bold",
        "business_types": ["creative-agency", "hospitality", "property"],
        "visual_tags": ["full-bleed", "background-image", "overlay"],
    },
    "heroes/minimal-centered": {
        "name": "Minimal Centered Hero",
        "category": "hero",
        "variant_name": "minimal-centered",
        "file": "heroes/minimal-centered.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Centered minimal hero with restrained typography and single CTA.",
        "mood": "calm",
        "business_types": ["saas", "tech-consulting", "design-studio"],
        "visual_tags": ["centered", "minimal", "single-cta"],
    },
    "heroes/stat-bar": {
        "name": "Hero With Stat Bar",
        "category": "hero",
        "variant_name": "stat-bar",
        "file": "heroes/stat-bar.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Hero section paired with a compact statistics strip for credibility.",
        "mood": "confident",
        "business_types": ["fintech", "b2b-services", "recruitment"],
        "visual_tags": ["stats", "metrics", "split"],
    },
    "features/3col-icons": {
        "name": "Three Column Icons",
        "category": "feature",
        "variant_name": "3col-icons",
        "file": "features/3col-icons.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Three-column feature grid with icons and short blurbs.",
        "mood": "clear",
        "business_types": ["saas", "it-support", "professional-services"],
        "visual_tags": ["grid", "icons", "three-column"],
    },
    "features/2col-images": {
        "name": "Two Column Images",
        "category": "feature",
        "variant_name": "2col-images",
        "file": "features/2col-images.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Two-column layout alternating imagery with concise copy blocks.",
        "mood": "warm",
        "business_types": ["retail", "hospitality", "healthcare"],
        "visual_tags": ["two-column", "imagery", "editorial"],
    },
    "features/alternating-text-image": {
        "name": "Alternating Text And Image",
        "category": "feature",
        "variant_name": "alternating-text-image",
        "file": "features/alternating-text-image.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Stacked rows that alternate text and image for narrative pacing.",
        "mood": "editorial",
        "business_types": ["manufacturing", "logistics", "education"],
        "visual_tags": ["zig-zag", "alternating", "long-form"],
    },
    "social-proof/testimonial-single": {
        "name": "Single Testimonial",
        "category": "social-proof",
        "variant_name": "testimonial-single",
        "file": "social-proof/testimonial-single.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Single highlighted testimonial with attribution and role.",
        "mood": "trustworthy",
        "business_types": ["professional-services", "saas", "coaching"],
        "visual_tags": ["quote", "avatar", "attribution"],
    },
    "social-proof/testimonial-grid": {
        "name": "Testimonial Grid",
        "category": "social-proof",
        "variant_name": "testimonial-grid",
        "file": "social-proof/testimonial-grid.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Grid of compact testimonials for dense social proof.",
        "mood": "friendly",
        "business_types": ["ecommerce", "marketplace", "local-services"],
        "visual_tags": ["grid", "cards", "quotes"],
    },
    "social-proof/stat-bar": {
        "name": "Social Proof Stat Bar",
        "category": "social-proof",
        "variant_name": "stat-bar",
        "file": "social-proof/stat-bar.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Horizontal strip of headline metrics for credibility.",
        "mood": "assertive",
        "business_types": ["b2b", "fintech", "recruitment"],
        "visual_tags": ["metrics", "inline", "numbers"],
    },
    "social-proof/logo-strip": {
        "name": "Logo Strip",
        "category": "social-proof",
        "variant_name": "logo-strip",
        "file": "social-proof/logo-strip.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Row of client or partner logos for lightweight trust signalling.",
        "mood": "neutral",
        "business_types": ["saas", "agency", "enterprise-vendor"],
        "visual_tags": ["logos", "marquee", "mono"],
    },
    "cta/centered": {
        "name": "Centered CTA",
        "category": "cta",
        "variant_name": "centered",
        "file": "cta/centered.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Centered call-to-action block with primary button and supporting line.",
        "mood": "direct",
        "business_types": ["saas", "lead-gen", "events"],
        "visual_tags": ["centered", "button", "contrast-band"],
    },
    "cta/split-with-form": {
        "name": "Split CTA With Form",
        "category": "cta",
        "variant_name": "split-with-form",
        "file": "cta/split-with-form.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Split layout pairing persuasive copy with a compact lead form.",
        "mood": "conversion-focused",
        "business_types": ["b2b-services", "property", "finance"],
        "visual_tags": ["split", "form", "lead-capture"],
    },
    "contact/simple-form": {
        "name": "Simple Contact Form",
        "category": "contact",
        "variant_name": "simple-form",
        "file": "contact/simple-form.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Straightforward stacked contact form with minimal framing.",
        "mood": "approachable",
        "business_types": ["local-services", "trades", "clinics"],
        "visual_tags": ["form", "stacked", "simple"],
    },
    "contact/split-contact": {
        "name": "Split Contact Section",
        "category": "contact",
        "variant_name": "split-contact",
        "file": "contact/split-contact.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Split layout with contact details alongside a form or map slot.",
        "mood": "professional",
        "business_types": ["law-firm", "accountancy", "consultancy"],
        "visual_tags": ["split", "details", "form"],
    },
    "navigation/sticky-simple": {
        "name": "Sticky Simple Navigation",
        "category": "navigation",
        "variant_name": "sticky-simple",
        "file": "navigation/sticky-simple.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Sticky top bar with logo and a short set of text links.",
        "mood": "clean",
        "business_types": ["saas", "portfolio", "publisher"],
        "visual_tags": ["sticky", "horizontal-nav", "minimal"],
    },
    "navigation/sticky-with-dropdown": {
        "name": "Sticky Navigation With Dropdown",
        "category": "navigation",
        "variant_name": "sticky-with-dropdown",
        "file": "navigation/sticky-with-dropdown.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Sticky navigation with dropdown menus for deeper IA.",
        "mood": "structured",
        "business_types": ["enterprise", "education", "government-supplier"],
        "visual_tags": ["sticky", "dropdown", "mega-lite"],
    },
    "footers/columns": {
        "name": "Multi-Column Footer",
        "category": "footer",
        "variant_name": "columns",
        "file": "footers/columns.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Multi-column footer with link groups and brand slot.",
        "mood": "informative",
        "business_types": ["saas", "publisher", "marketplace"],
        "visual_tags": ["columns", "link-groups", "newsletter-slot"],
    },
    "footers/minimal": {
        "name": "Minimal Footer",
        "category": "footer",
        "variant_name": "minimal",
        "file": "footers/minimal.html",
        "source": "hyperui",
        "license": "MIT",
        "description": "Single-line minimal footer for lightweight pages.",
        "mood": "quiet",
        "business_types": ["startup", "portfolio", "micro-saas"],
        "visual_tags": ["single-row", "legal-links"],
    },
}
